FROM ollama/ollama

ARG OLLAMA_MODEL=falcon3:7b

RUN echo '#!/bin/sh' > /entrypoint.sh && \
    echo '' >> /entrypoint.sh && \
    echo '# Start server in background' >> /entrypoint.sh && \
    echo 'ollama serve &' >> /entrypoint.sh && \
    echo '' >> /entrypoint.sh && \
    echo '# Wait for server to be ready' >> /entrypoint.sh && \
    echo 'sleep 10' >> /entrypoint.sh && \
    echo '' >> /entrypoint.sh && \
    echo '# Pull model' >> /entrypoint.sh && \
    echo 'ollama pull '"${OLLAMA_MODEL}"'' >> /entrypoint.sh && \
    echo '' >> /entrypoint.sh && \
    echo '# Kill initial server' >> /entrypoint.sh && \
    echo 'pkill ollama' >> /entrypoint.sh && \
    echo '' >> /entrypoint.sh && \
    echo '# Start server again in foreground' >> /entrypoint.sh && \
    echo 'exec ollama serve' >> /entrypoint.sh && \
    chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]